version: '3'
services:
  tedsearch:
      image: tedsearch
      expose:
        - 8080
  proxy:
      image: nginx:1.23.3-alpine-slim
      # image: nginx:1.23.3
      ports:
        - 80:80
      volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./static:/usr/share/nginx/html/static
